general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
}

listener {
    timeout = 300                            # in seconds.
		on-timeout = loginctl lock-session
}
