[general]
import = [
  "~/config/.config/alacritty/themes/tokyonight_moon.toml"
]
[font]
size = 12.0

[env]
TERM = "xterm-256color"

[font.normal]
family = "MesloLGS Nerd Font Mono"

[window]
padding.x = 5
padding.y = 5
dynamic_title = false

[cursor.style]
shape = "Block"
