[general]
import = [
  "~/dotfiles/.config/alacritty/tokyionight-storm.toml"
]
[font]
size = 13.0

[env]
TERM = "xterm-256color"

[font.normal]
family = "MesloLGS Nerd Font Mono"

[window]
padding.x = 5
padding.y = 5

