[general]
import = [
  "~/dotfiles/.config/alacritty/themes/dayfox.toml"
]
[font]
size = 14.0

[env]
TERM = "xterm-256color"

[font.normal]
family = "MesloLGS Nerd Font Mono"

[window]
padding.x = 5
padding.y = 5

[terminal]
shell.program = "/usr/bin/fish"

[cursor.style]
shape = "Block"
